Loaded dependency [python3/3.9.19]: sqlite3/3.46.0
Loaded dependency [python3/3.9.19]: gcc/12.4.0-binutils-2.42
Loaded module: python3/3.9.19

Loading python3/3.9.19
  Loading requirement: sqlite3/3.46.0 gcc/12.4.0-binutils-2.42
Loaded module: cuda/11.8
Loaded module: cudnn/v8.8.0-prod-cuda-11.X
/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/nn/modules/lazy.py:181: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
  0%|          | 0/63 [00:00<?, ?it/s]  0%|          | 0/63 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/zhome/eb/a/203134/DL_project/DL_final/cli.py", line 181, in <module>
    core_function()  
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/zhome/eb/a/203134/DL_project/DL_final/cli.py", line 147, in core_function
    loss, accuracy_score, auprc_score, auc_score = train_test(
  File "/zhome/eb/a/203134/DL_project/DL_final/mortality_classification.py", line 50, in train_test
    val_loss, model = train(
  File "/zhome/eb/a/203134/DL_project/DL_final/mortality_classification.py", line 165, in train
    predictions = model(
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/zhome/eb/a/203134/DL_project/DL_final/models/deep_set_attention.py", line 274, in forward
    attentions = self.attention(collected_values, segment_ids, lengths)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/zhome/eb/a/203134/DL_project/DL_final/models/deep_set_attention.py", line 155, in forward
    return [
  File "/zhome/eb/a/203134/DL_project/DL_final/models/deep_set_attention.py", line 156, in <listcomp>
    segment_softmax(pre_attn, segment_ids) for pre_attn in preattn.unbind(1)
  File "/zhome/eb/a/203134/DL_project/DL_final/models/seft_utils.py", line 11, in segment_softmax
    max_values = torch_scatter.scatter_max(data, segment_ids, dim=0)[0]
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/zhome/eb/a/203134/venvdef/lib/python3.9/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: Not compiled with CUDA support
